#!/usr/bin/env bash

# Exit on error
set -e

[ "${ZSH_VERSION}" = "" ] && this_dir=`dirname ${BASH_SOURCE[0]}` || this_dir=`dirname ${(%):-%N}`
. ${this_dir}/shell_setup.sh
. ${this_dir}/prelude.sh

function usage() {
    echo "Usage:"
    echo ""
    echo "  dummy_srs_setup [circuit-name] [options]"
    echo ""
    echo "Options:"
    echo ""
    echo "  --help         Print this message"
    echo "  --dry-run,-n      Dry-run mode (for testing, export DRY_RUN=1)"
    echo ""
}

circuit_name=all
while [[ $# -gt 0 ]] ; do
    case $1 in
        -h|--help)
            usage
            exit 0
            ;;
        -n|--dry-run)
            export DRY_RUN=1
            shift
            ;;
        *)
            circuit_name=$1
            shift
            ;;
    esac
done

# Create dummy SRS files in the current dir, as symlinks to files in the
# directory ../_srs.

# 1 - circuit name
# 2 - degree
function create_srs_for_circuit() {
    circuit_name=$1
    degree=$2
    srs_file=${circuit_name}.srs

    # If an srs file already exists, we're done.  Otherwise, create one, using
    # the cache of files in ../_srs.
    if ! [ -e ${srs_file} ] ; then

        # If the real underlying file does not exist, create it
        real_srs_file=../_srs/${degree}.srs
        if ! [ -e ${real_srs_file} ] ; then
            echo "Creating srs file ${real_srs_file}..."
            mkdir -p ../_srs
            ${PROVER} srs generate -d ${degree} -s ${real_srs_file}
        else
            echo "Real srs file ${real_srs_file} already exists."
        fi

        # Symlink
        echo "Linking ${srs_file} -> ${real_srs_file}"
        ln -s ${real_srs_file} ${srs_file}
    else
        echo "File ${srs_file} already exists in current dir.  Skipping."
        return
    fi
}

# 1 - circuit name
# 2 - config file
function get_circuit_degree() {
    circuit_name=$1
    config_file=$2
    degree=`cat ${config_file} | jq .${circuit_name}_config.degree_bits`
    echo ${degree}
}

# If a config file exists, create a dummy srs for it.
#
# 1 - circuit name
function create_srs_if_config_file() {
    circuit_name=$1

    if [ "${DRY_RUN}" == "1" ] ; then
        echo "Dry-run mode.  Skipping SRS generation."
        exit 0
    fi

    config_file=upa_config.json
    if [ -e ${config_file} ] ; then
        echo "Found config file ${config_file}"
        degree=`get_circuit_degree ${circuit_name} ${config_file}`
        create_srs_for_circuit ${circuit_name} ${degree}
    else
        echo "No config file ${config_file}.  Cannot generate dummy srs"
        exit 1
    fi
}

if [ "${PROVER}" == "" ] ; then
    echo "PROVER env var not set.  Source scripts/shell_setup.sh"
    exit 1
fi

if [ "${circuit_name}" == "all" ] ; then
    echo "Setting up srs for all circuits"
    create_srs_if_config_file bv
    create_srs_if_config_file keccak
    create_srs_if_config_file outer
else
    echo "Setting up srs for circuit: ${circuit_name}"
    create_srs_if_config_file ${circuit_name}
fi
