#!/usr/bin/env bash

# Tests keygen, proving and verification

set -e
set -x

# Build
cargo build --release

# Shell setup
shopt -s expand_aliases
. ./scripts/shell_setup.sh
. ./scripts/prelude.sh

rm -rf _test_prover
mkdir -p _test_prover
pushd _test_prover

    # Get a default config if one is not present.
    if [ "${COMPUTE_SUBMISSION_ID}" == "1" ]; then
      cp ../tests/upa_config_2_with_submission_id.json upa_config.json
    else
      cp ../tests/upa_config_2.json upa_config.json
    fi

    [ -e upa_config.json ] || cp ../tests/upa_config_2.json upa_config.json
    inner_batch_size=`jq -r .inner_batch_size upa_config.json`
    max_num_inputs=`jq -r .max_num_app_public_inputs upa_config.json`
    outer_batch_size=`jq -r .outer_batch_size upa_config.json`

    if [ "${COMPUTE_SUBMISSION_ID}" == "1" ]; then
      submission_size=$((inner_batch_size * outer_batch_size))
      NUM_PROOF_IDS="--num-proof-ids ${submission_size}"
    fi

    # Create `inner_batch_size` (unsafe) keys.
    for i in $(seq 0 $(($inner_batch_size - 1))); do
      key_file="vk-${i}.unsafe.json"
      if [ $(($i % 2)) -eq 0 ]; then
        prover groth16 generate-fake-vk -i ${max_num_inputs} -v $key_file
      else
        prover groth16 generate-fake-vk -i $((${max_num_inputs} / 2)) -v $key_file -c
      fi
    done

    # Create `outer_batch_size` inner batches
    for j in $(seq 0 $(($outer_batch_size - 1))); do
      prover groth16 generate-proofs \
        -n ${inner_batch_size} \
        $(for i in $(seq 0 $(($inner_batch_size - 1))); do echo -v vk-${i}.unsafe.json; done) \
        -b inner-batch-${j}.json
    done

    batch_files=""
    for j in $(seq 0 $(($outer_batch_size - 1))); do
      batch_files+="--app-vk-proof-batch inner-batch-${j}.json "
    done
    echo ${batch_files}

    # Run keygen, prove and verify
    dummy_srs_setup
    prover full keygen ${PROVER_FLAGS}
    prover full prove ${PROVER_FLAGS} ${batch_files} ${NUM_PROOF_IDS}
    prover full verify ${PROVER_FLAGS}

    # Verify the intermediate ubv and keccak proofs
    for j in $(seq 0 $(($outer_batch_size - 1))); do
      proof_file="ubv.proof${j}"
      instance_file="ubv.proof.instance${j}"
      prover universal-batch-verifier verify ${PROVER_FLAGS} --proof ${proof_file} --instance ${instance_file}
    done
    prover keccak verify ${PROVER_FLAGS}

popd # _test_prover

set +x
set +e

echo "======================================"
echo "====            PASSED            ===="
echo "======================================"
