#!/usr/bin/env bash

# Updates the demo-app repo using the `build_standalone` script. Run
# this script after building `demo-app` and `upa`. At the end
# these changes will be committed but not yet pushed upstream.

# TODO: support writing to branches

set -x
set -e

DEMO_DIR="demo-app"
UPA_COMMIT_INFO=`git show --oneline -s HEAD`

rm -rf ${DEMO_DIR}

# Clone the demo repo, remove all files

git clone git@github.com:NebraZKP/demo-app.git ${DEMO_DIR}

pushd ${DEMO_DIR}
    git rm -r '*'
    git reset .
popd

# Create the standalone version

./scripts/build_standalone --registry --dont-delete

# Restore any files we want to keep from the original repo
pushd ${DEMO_DIR}
git checkout README.md
    pushd core
        git checkout .gitignore
        git checkout .env
        git checkout upa.instance
        git checkout demo-app.instance
        git checkout circuits || echo "No circuits in old repo"
    popd # core

    pushd frontend
        git checkout public/circuit.wasm
        git checkout public/circuit.zkey
        git checkout public/instances/demo-app.instance.json
        git checkout public/instances/upa.instance.json
    popd # frontend

    git add --all
    git commit -m "Demo update from UPA commit: ${UPA_COMMIT_INFO}"
popd # DEMO_DIR

set +x
set +e
