name: circuit tests

on:
  push:
    paths:
    - 'Cargo.toml'
    - 'circuits/**'
    - .github/workflows/circuits.yml
    - .rustfmt.toml

concurrency:
    cancel-in-progress: true
    group: ${{github.workflow}}-${{github.ref}}

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings -A unknown-lints
  RUST_BACKTRACE: full

jobs:
  start-runner:
    name: Start EC2 runner
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.AWS_GITHUB_TOKEN }}
          ec2-image-id: ${{ vars.EC2_IMAGE_ID }}
          ec2-instance-type: c7a.4xlarge
          subnet-id: ${{ vars.SUBNET_ID }}
          security-group-id: ${{ vars.SECURITY_GROUP_ID }}

  # Build, check and test the circuit test code
  circuit-tests:
    needs: start-runner # required to start the main job when the runner is ready
    runs-on: ${{ needs.start-runner.outputs.label }}

    defaults:
      run:
        working-directory: circuits

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # For EC2 runner
      - name: Set HOME env variable
        run: |
          echo "HOME=/root" >> ${GITHUB_ENV}
      # For EC2 runner
      - name: Add pre-installed cargo and rustc executables to github path.
        run: |
          echo "$HOME/.cargo/bin" >> ${GITHUB_PATH}

      - name: Cargo cache
        uses: Swatinem/rust-cache@v2

      - name: Run rustfmt
        run: |
          cargo fmt --check

      - name: Check for dangerous Field traits
        run: |
          if (git grep -n PrimeField | grep -v EccPrimeField | grep -v use) ; then echo "Use crate::EccPrimeField everywhere" ; exit 1 ; fi

      - name: Cargo sort
        run: |
          cargo +stable install cargo-sort
          cargo +stable sort --workspace --check

      - name: Run clippy
        run: |
          cargo clippy --no-deps
          cargo clippy --no-deps --tests
          cargo clippy --no-deps --benches
          
      - name: Run unit tests
        run: |
          cargo test --release -- --test-threads=1 --show-output

  stop-runner:
    name: Stop EC2 runner
    needs:
      - start-runner
      - circuit-tests
    runs-on: ubuntu-latest
    if: ${{ always() }} # required to stop the runner even if an error happened in the previous jobs
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.AWS_GITHUB_TOKEN }}
          label: ${{ needs.start-runner.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner.outputs.ec2-instance-id }}
