name: contract tests

on:
  push:
    paths:
    - package.json
    - 'upa/**'
    - .github/workflows/contracts.yml

concurrency:
    cancel-in-progress: true
    group: ${{github.workflow}}-${{github.ref}}

jobs:
  sdk-tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: upa

    strategy:
      fail-fast: true
      matrix:
        node-version: [20]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"

      - name: install
        run: |
          yarn

      - name: code check
        run: |
          yarn lint

      - name: format check
        run: |
          yarn run format
          git diff --no-ext-diff --ignore-cr-at-eol -- **.ts > format.diff
          echo "DIFF:" && cat format.diff
          ! [ -s format.diff ]

      # - name: run slither
      #   run: |
      #     yarn slither

      - name: build
        run: |
          yarn build

      - name: run contract and typescript tests
        run: |
          yarn test

      - name: run test_upa
        run: |
          ./scripts/test_upa

      - name: run test_dev_aggregator
        run: |
          ./scripts/test_dev_aggregator

      - name: run package test
        run: |
          ./scripts/test_package
